         const teamColours = {
            "Arsenal": { bg: "#EF0107", fg: "#FFFFFF" },
            "Aston Villa": { bg: "#95BFE5", fg: "#670E36" },
            "AFC Bournemouth": { bg: "#DA291C", fg: "#000000" },
            "Birmingham City": { bg: "#20377eff", fg: "#fec700ff" },
            "Blackburn Rovers": { bg: "#003366", fg: "#FFFFFF" },
            "Brighton & Hove Albion": { bg: "#0057B8", fg: "#FFFFFF" },
            "Bristol City": { bg: "#E21A23", fg: "#ffffff" },
            "Brentford": { bg: "#e30613", fg: "#ffffff" },
            "Burnley": { bg: "#6C1D45", fg: "#99D6EA" },
            "Coventry City": { bg: "#059DD9", fg: "#FFFFFF" },
            "Charlton Athletic": { bg: "#d4021d", fg: "#000000" },
            "Chelsea": { bg: "#034694", fg: "#FFFFFF" },
            "Crystal Palace": { bg: "#1B458F", fg: "#C4122E" },
            "Derby County": { bg: "#FFFFFF", fg: "#231f20" },
            "Everton": { bg: "#003399", fg: "#FFFFFF" },
            "Fulham": { bg: "#FFFFFF", fg: "#000000" },
            "Hull City": { bg: "#f5971d", fg: "#231f20" },
            "Ipswich Town": { bg: "#0e00f7", fg: "#FFFFFF" },
            "Leeds United": { bg: "#FFFFFF", fg: "#0060A9" },
            "Leicester City": { bg: "#0101e8", fg: "#fdbe11" },
            "Liverpool": { bg: "#C8102E", fg: "#00B2A9" },
            "Manchester City": { bg: "#6CABDD", fg: "#1C2C5B" },
            "Manchester United": { bg: "#DA291C", fg: "#FBE122" },
            "Middlesbrough": { bg: "#DE1B22", fg: "#FFFFFF" },
            "Millwall": { bg: "#00194A", fg: "#FFFFFF" },
            "Newcastle United": { bg: "#241F20", fg: "#FFFFFF" },
            "Norwich City": { bg: "#ffee00", fg: "#88ff33" },
            "Nottingham Forest": { bg: "#E53233", fg: "#FFFFFF" },
            "Oxford United": { bg: "#ffdd00", fg: "#214080" },
            "Portsmouth": { bg: "#001489", fg: "#e1e4f3" },
            "Preston North End": { bg: "#edededff", fg: "#002156" },
            "Queens Park Rangers": { bg: "#0c00cd", fg: "#FFFFFF" },
            "Sheffield United": { bg: "#EE2737", fg: "#FFFFFF" },
            "Sheffield Wednesday": { bg: "#0e62aa", fg: "#FFFFFF" },
            "Southampton": { bg: "#ed1a3b", fg: "#FFFFFF" },
            "Stoke City": { bg: "#E03A3E", fg: "#FFFFFF" },
            "Sunderland": { bg: "#FFFFFF", fg: "#EB172B" },
            "Swansea": { bg: "#FFFFFF", fg: "#222222" },
            "Tottenham Hotspur": { bg: "#132257", fg: "#FFFFFF" },
            "Watford": { bg: "#fbee23", fg: "#ff4800ff" },
            "West Ham United": { bg: "#7A263A", fg: "#1BB1E7" },
            "West Bromwich Albion": { bg: "#060067", fg: "#FFFFFF" },
            "Wolverhampton Wanderers": { bg: "#FDB913", fg: "#231F20" },
            "Wrexham": { bg: "#D50F25", fg: "#FFFFFF" },
            "draw": { bg: "#A9A5AD", fg: "#FFFFFF" },
        };

        const teamLogos = {
            "AFC Bournemouth": "/Logos/PremierLeague/600.png",
            "Arsenal": "/Logos/PremierLeague/602.png",
            "Aston Villa": "/Logos/PremierLeague/603.png",
            "Birmingham City": "/Logos/Championship/609.png",
            "Blackburn Rovers": "/Logos/Championship/612.png",
            "Brentford": "/Logos/PremierLeague/617.png",
            "Brighton & Hove Albion": "/Logos/PremierLeague/618.png",
            "Bristol City": "/Logos/Championship/619.png",
            "Burnley": "/Logos/PremierLeague/622.png",
            "Charlton Athletic": "/Logos/Championship/628.png",
            "Chelsea": "/Logos/PremierLeague/630.png",
            "Coventry City": "/Logos/Championship/639.png",
            "Crystal Palace": "/Logos/PremierLeague/642.png",
            "Derby County": "/Logos/Championship/645.png",
            "Everton": "/Logos/PremierLeague/650.png",
            "Fulham": "/Logos/PremierLeague/654.png",
            "Hull City": "/Logos/Championship/665.png",
            "Ipswich Town": "/Logos/Championship/667.png",
            "Leeds United": "/Logos/PremierLeague/671.png",
            "Leicester City": "/Logos/Championship/673.png",
            "Liverpool": "/Logos/PremierLeague/676.png",
            "Manchester City": "/Logos/PremierLeague/679.png",
            "Manchester United": "/Logos/PremierLeague/680.png",
            "Middlesbrough": "/Logos/Championship/685.png",
            "Millwall": "/Logos/Championship/686.png",
            "Newcastle United": "/Logos/PremierLeague/688.png",
            "Norwich City": "/Logos/Championship/691.png",
            "Nottingham Forest": "/Logos/PremierLeague/692.png",
            "Oxford United": "/Logos/Championship/695.png",
            "Portsmouth": "/Logos/Championship/699.png",
            "Preston North End": "/Logos/Championship/700.png",
            "Queens Park Rangers": "/Logos/Championship/701.png",
            "Sheffield United": "/Logos/Championship/708.png",
            "Sheffield Wednesday": "/Logos/Championship/709.png",
            "Southampton": "/Logos/Championship/713.png",
            "Stoke City": "/Logos/Championship/721.png",
            "Sunderland": "/Logos/PremierLeague/722.png",
            "Swansea City": "/Logos/Championship/724.png",
            "Tottenham Hotspur": "/Logos/PremierLeague/728.png",
            "Watford": "/Logos/Championship/732.png",
            "West Bromwich Albion": "/Logos/Championship/734.png",
            "West Ham United": "/Logos/PremierLeague/735.png",
            "Wolverhampton Wanderers": "/Logos/PremierLeague/740.png",
            "Wrexham": "/Logos/Championship/741.png",
        };